# Generated by Django 5.0.6 on 2026-02-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_type', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup'), ('Friendly', 'Friendly')], max_length=10)),
                ('venue_type', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Neutral', 'Neutral')], max_length=10)),
                ('location', models.CharField(max_length=150)),
                ('our_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('training_type', models.CharField(choices=[('Attacking', 'Attacking'), ('Defending', 'Defending'), ('Passing', 'Passing'), ('Fitness', 'Fitness'), ('Match Sim', 'Match Sim')], max_length=15)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.training')),
            ],
            options={
                'unique_together': {('player', 'training')},
            },
        ),
    ]
