# Generated by Django 5.0.6 on 2026-02-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingattendance',
            old_name='notes',
            new_name='player_notes',
        ),
    ]
